version: "3.3"
services: 
  fleursdici:
    image: mydrox/fleursdici:dev.1.0.0
    build:
      context: ../
      dockerfile: deploy/dev/Dockerfile
    env_file:
      - ../.env.local
    ports:
      - 3000:3000

  fleursdici-postgres:
    env_file:
      - ../.env.local.db
    ports:
      - 5432:5432

  fleursdici-pgadmin:
    env_file:
      - ../.env.local.db
    ports:
      - 5050:5050
