version: "3.3"
services: 
  fleursdici:
    image: mydrox/fleursdici:1.0.0
    build:
      context: ../
      dockerfile: deploy/prod/Dockerfile
    env_file:
      - .env
    
  fleursdici-postgres:
    env_file:
      - ../.env.db
    ports:
      - 5432:5432

  fleursdici-pgadmin:
    logging: 
      driver: none
    env_file:
      - ../.env.db
    ports:
      - 5050:5050