version: "3.3"
services: 
  fleursdici:
    build:
      args: 
        WORK_DIR: /go/src/github.com/MydroX/fleursdici
    container_name: fleursdici
    volumes: 
      - ../.:/go/src/github.com/MydroX/fleursdici
    networks: 
      - fleursdici
    depends_on:
      - fleursdici-postgres

  fleursdici-postgres:
    image: postgres:14.5-alpine3.16
    container_name: fleursdici-postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - fleursdici
  
  fleursdici-pgadmin:
    image: dpage/pgadmin4:6.12
    container_name: fleursdici-pgadmin
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - fleursdici
    depends_on:
      - fleursdici-postgres

volumes:
  postgres:
  pgadmin:

networks:
  fleursdici:
    external: true
  